stages:
  - build
  - test
  - deploy

image: node:13.10.1-stretch

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - node_modules/
      - build/

test:
  stage: test
  script:
    - yarn test

deploy:
  stage: deploy
  environment: Production
  script:
    - npm -g config set user root
    - npm i -g  firebase-tools
    - yarn
    - yarn run build
    - firebase use $FIREBASE_DEPLOY_NAME --token $FIREBASE_DEPLOY_KEY
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_DEPLOY_KEY
  only:
    - master
