stages:
  - build
  - test
  - deploy

image: node:13.10.1-stretch

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - node_modules/
      - build/
  only:
    - develop

test:
  stage: test
  script:
    - yarn test

deploy:
  stage: deploy
  environment: Production
  script:
    - npm install -g firebase-tools
    - npm install -g bower
    - yarn
    - bower install --allow-root
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  only:
    - master
